@ECHO OFF
SET WATCOM=F:\watcom
SET os2tk=F:\os2tk45

SET PATH=%WATCOM%\BINP;%WATCOM%\BINW;%os2tk%\bin;%PATH%
SET INCLUDE=%WATCOM%\H;%WATCOM%\H\OS2
SET FINCLUDE=%WATCOM%\SRC\FORTRAN
SET EDPATH=%WATCOM%\EDDAT
SET HELP=%WATCOM%\BINP\HELP;%HELP%
SET BOOKSHELF=%WATCOM%\BINP\HELP;%BOOKSHELF%
SET BEGINLIBPATH=%WATCOM%\BINP\DLL

cmd