.TH "SDL_GL_SwapBuffers" "3" "Mon 12 Mar 2001, 01:04" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GL_SwapBuffers\- Swap OpenGL framebuffers/Update Display
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_GL_SwapBuffers\fP\fR(\fBvoid \fR);
.SH "DESCRIPTION"
.PP
Swap the OpenGL buffers, if double-buffering is supported\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_SetVideoMode\fP\fR, \fI\fBSDL_GL_SetAttribute\fP\fR
...\" created by instant / docbook-to-man, Mon 12 Mar 2001, 01:04
