.TH "SDL_GetKeyName" "3" "Mon 12 Mar 2001, 01:03" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetKeyName\- Get the name of an SDL virtual keysym
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBchar *\fBSDL_GetKeyName\fP\fR(\fBSDLKey key\fR);
.SH "DESCRIPTION"
.PP
Returns the SDL-defined name of the \fI\fBSDLKey\fR\fR \fBkey\fR\&.
.SH "SEE ALSO"
.PP
\fI\fBSDLKey\fR\fR
...\" created by instant / docbook-to-man, Mon 12 Mar 2001, 01:03
