.TH "SDL_CDPause" "3" "Mon 12 Mar 2001, 01:02" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CDPause\- Pauses a CDROM
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBint \fBSDL_CDPause\fP\fR(\fBSDL_CD *cdrom\fR);
.SH "DESCRIPTION"
.PP
Pauses play on the given \fBcdrom\fR\&.
.SH "RETURN VALUE"
.PP
Returns \fB0\fR on success, or \fB-1\fR on an error\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CDPlay\fP\fR, \fI\fBSDL_CDResume\fP\fR
...\" created by instant / docbook-to-man, Mon 12 Mar 2001, 01:02
