.TH "SDL_GetTicks" "3" "Mon 12 Mar 2001, 01:04" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_GetTicks\- Get the number of milliseconds since the SDL library initialization\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBUint32 \fBSDL_GetTicks\fP\fR(\fBvoid\fR)
.SH "DESCRIPTION"
.PP
Get the number of milliseconds since the SDL library initialization\&. Note that this value wraps if the program runs for more than ~49 days\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_Delay\fP\fR
...\" created by instant / docbook-to-man, Mon 12 Mar 2001, 01:04
