.TH "SDL_CloseAudio" "3" "Mon 12 Mar 2001, 01:02" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_CloseAudio\- Shuts down audio processing and closes the audio device\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_CloseAudio\fP\fR(\fBvoid\fR)
.SH "DESCRIPTION"
.PP
This function shuts down audio processing and closes the audio device\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_OpenAudio\fP\fR 
...\" created by instant / docbook-to-man, Mon 12 Mar 2001, 01:02
