.TH "SDL_UpdateRects" "3" "Mon 12 Mar 2001, 01:04" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_UpdateRects\- Makes sure the given list of rectangles is updated on the given screen\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_UpdateRects\fP\fR(\fBSDL_Surface *screen, int numrects, SDL_Rect *rects\fR);
.SH "DESCRIPTION"
.PP
Makes sure the given list of rectangles is updated on the given screen\&.
.PP
This function should not be called while \fBscreen\fR is \fIlocked\fR\&. 
.SH "SEE ALSO"
.PP
\fI\fBSDL_UpdateRect\fP\fR, \fI\fBSDL_Rect\fR\fR, \fI\fBSDL_Surface\fR\fR, \fI\fBSDL_LockSurface\fP\fR
...\" created by instant / docbook-to-man, Mon 12 Mar 2001, 01:04
