.TH "SDL_Delay" "3" "Mon 12 Mar 2001, 01:04" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_Delay\- Wait a specified number of milliseconds before returning\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_Delay\fP\fR(\fBUint32 ms\fR);
.SH "DESCRIPTION"
.PP
Wait a specified number of milliseconds before returning\&. \fBSDL_Delay\fP will wait at \fIleast\fP the specified time, but possible longer due to OS scheduling\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_AddTimer\fP\fR
...\" created by instant / docbook-to-man, Mon 12 Mar 2001, 01:04
