.TH "SDL_WM_SetCaption" "3" "Mon 12 Mar 2001, 01:05" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_WM_SetCaption\- Sets the window tile and icon name\&.
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
.sp
\fBvoid \fBSDL_WM_SetCaption\fP\fR(\fBconst char *title, const char *icon\fR);
.SH "DESCRIPTION"
.PP
Sets the title-bar and icon name of the display window\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_WM_GetCaption\fP\fR, \fI\fBSDL_WM_SetIcon\fP\fR
...\" created by instant / docbook-to-man, Mon 12 Mar 2001, 01:05
