.TH "SDL_DestroyCond" "3" "Mon 12 Mar 2001, 01:03" "SDL" "SDL API Reference" 
.SH "NAME"
SDL_DestroyCond\- Destroy a condition variable
.SH "SYNOPSIS"
.PP
\fB#include "SDL\&.h"
#include "SDL_thread\&.h"
.sp
\fBvoid \fBSDL_DestroyCond\fP\fR(\fBSDL_cond *cond\fR);
.SH "DESCRIPTION"
.PP
Destroys a condition variable\&.
.SH "SEE ALSO"
.PP
\fI\fBSDL_CreateCond\fP\fR
...\" created by instant / docbook-to-man, Mon 12 Mar 2001, 01:03
