SDLTest : touchSimp.c touchPong.c
	gcc gestureTest.c -o gestureTest `sdl-config --cflags --libs` -g
	gcc touchTest.c -o touchTest `sdl-config --cflags --libs` -g		
	gcc touchSimp.c -o touchSimp `sdl-config --cflags --libs` -g
	gcc touchPong.c -o touchPong `sdl-config --cflags --libs` -g
	gcc parseDevicesTest.c -o parseDevicesTest -g


