SDLTest : touchSimp.c touchPong.c
	gcc touchTest.c -o touchTest `sdl-config --cflags --libs` -g		
	gcc touchSimp.c -o touchSimp `sdl-config --cflags --libs` -g
	gcc touchPong.c -o touchPong `sdl-config --cflags --libs` -g

